print("welcome to calvert hall ")
name = input("what is your name? ")
gradyear = input("what year do you graduate? ")
standing = input("what is your class standing? ")
email = input("what is your email? ")
print(f"My name is {name}, I graduate in {gradyear}, my class standing is {standing}, and my email is {email}")
x = input("what is num1 ")
y = input("what is num2 ")
x = int(x)
y = int(y)
z = x + y
print(z)
